### PR TITLE
Moved Blockly, jquery, font-awesome into Bower and added Gulp/Browserify

### PR DESCRIPTION
**Pull request by lynnaloo**

### CODE REVIEW

**Comment by lynnaloo** [comment]
This isn't ready to be merged. I'm getting this error in Blockly: `Uncaught Error: '180' is not a valid hex color`

**Comment by makenai** [comment]
I've moved blockly to a napa install, which means it will always get the latest version from git. I don't bower much, but I thought it might be nice to have the bower stuff and the one from napa in the same place, so I made bower_components 'vendor'. How do these changes strike you stylistically?

https://github.com/makenai/robotnik/commit/7579be026f4c9ff232b5aac46b236204a6fe951b

**Comment by lynnaloo** [comment]
Napa might be a good solution to getting Ace out of source control as well.

**Comment by makenai** [comment]
I'll look into that next, but I also want to look into codemirror again since I've heard it might be a little cleaner.

**Comment by lynnaloo** [comment]
@makenai OK, I merged your changes and moved `vendor` down be parallel to `js`

**Comment by lynnaloo** [comment]
Resolves #13

**Pull request merged**
